---
- name: 'Install SNMP and prerequisites'
  apt:
    name:
      - 'snmp'
      - 'snmp-mibs-downloader'
    state: 'present'

- name: 'Configure SNMP'
  template:
    src: 'snmpd.j2'
    dest: '/etc/snmp/snmpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart SNMP'
