---
- name: add 2.4 config
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version >= "16.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
  template:
    src: ../templates/apache-2.4.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    mode: 0644

- name: add 2.2 config
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
  template:
    src: ../templates/apache-2.2.j2
    dest: /etc/apache2/sites-available/default
    owner: root
    mode: 0644

- name: enable php module mcrypt
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version >= "16.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
  command: phpenmod mcrypt

- name: enable php module mcrypt
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
  command: php5enmod mcrypt

- name: enable apache modules
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version >= "16.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
  apache2_module:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: 'mpm_event', state: 'absent' }
    - { name: 'mpm_prefork', state: 'present' }
    - { name: 'php7.0', state: 'present' }
    - { name: 'rewrite', state: 'present' }
  notify: restart apache2

- name: enable apache modules
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04") or
          (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
  apache2_module:
    name: rewrite
    state: present
  notify: restart apache2
