---

repos:
  - repo: local
    hooks:
      - id: forbid-files-yaml
        name: (files) -- yaml files has to have yml extension
        entry: forbid-files-yaml
        language: fail
        files: '.*\/.*yaml$'


  - repo: git://github.com/pre-commit/pre-commit.git
    rev: v2.3.0
    hooks:
      - id: validate_manifest
        name: (pre-commit) -- validate manifest


  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        name: (git) -- forbid adding large files
      - id: forbid-new-submodules
        name: (git) -- forbid using submodules
      - id: check-merge-conflict
        name: (git) -- forbid commiting with merge-conflicts
      - id: no-commit-to-branch
        name: (git) -- forbid commiting to master, develop or release directly
        args: [-b, develop, -b, master, -b, release]
      - id: check-executables-have-shebangs
        name: (file) -- check if executables have interpreter mentioned
      - id: check-case-conflict
        name: (file) -- verify case-sensitive conflicts
      - id: check-symlinks
        name: (file) -- look for empty symlinks
      - id: trailing-whitespace
        name: (code) -- fix trailing whitespace
      - id: end-of-file-fixer
        name: (code) -- fix end-of-line
      - id: check-docstring-first
        name: (code) -- check document-string
      - id: check-json
        name: (code) -- verify JSON syntax
      - id: check-yaml
        name: (code) -- verify YAML syntax
      - id: requirements-txt-fixer
        name: (code) -- sort and fix requirements-txt
      - id: double-quote-string-fixer
        name: (code) -- fix double-quote-string
      - id: detect-private-key
        name: (security) -- detect private keys
      - id: requirements-txt-fixer
        name: (code) -- fix dependencies order


  - repo: git://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
        name: (code) -- check trailing-coma


  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-tabs
        name: (code) -- forbid tabs to be commited
        exclude: >
            (?x)^(
                .git/COMMIT_EDITMSG
            )$

      - id: remove-tabs
        name: (code) -- replace tabs with spaces automatically
        exclude: >
            (?x)^(
                .git/COMMIT_EDITMSG
            )$


  - repo: git://github.com/ansible/ansible-lint
    rev: v4.3.0a0
    hooks:
      - id: ansible-lint
        name: (ansible) -- lint the code
        files: \.(yaml|yml)$
        args: [-c=.tests/.ansible-lint]


  - repo: git://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
      - id: encryption-check
        name: (ansible) -- verify that vault files are really encrypted


  - repo: git://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
        name: (gitlint) -- lint commit message
        args: [-C=.tests/.gitlint]


  - repo: git://github.com/adrienverge/yamllint
    rev: v1.23.0
    hooks:
      - id: yamllint
        name: (code) -- lint the yaml files
        args: [-c=.tests/.yamllint]
