---
- name:
  hosts: 'vcenter'
  gather_facts: no
  connection: 'local'

  tasks:
    - name: 'Gather facts'
      local_action:
        module: 'vmware_vm_facts'
        hostname: '{{ hostname }}'
        username: '{{ user }}'
        password: '{{ pass }}'

    - name: 'Create new VM'
      vmware_guest:
        hostname: '{{ hostname }}'
        username: '{{ user }}'
        password: '{{ pass }}'
        validate_certs: no
        esxi_hostname: '{{ esxi_hostname }}'
        datacenter: '{{ datacenter }}'
        name: 'testingvm'
        state: 'present'
        guest_id: 'ubuntu64Guest'
        disk:
          - size_gb: 10
            type: 'thin'
            datastore: '{{ datastore }}'
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: 'paravirtual'
        networks:
          - name: '{{ network }}'
            ip: '192.168.1.52'
            netmask: '255.255.255.192'
      register: 'deploy'

    - name: 'Shutdown new VM'
      vmware_guest:
        hostname: '{{ hostname }}'
        username: '{{ user }}'
        password: '{{ pass }}'
        validate_certs: no
        datacenter: '{{ datacenter }}'
        name: 'testingvm'
        state: 'poweredoff'

    - name: 'Remove new VM'
      vmware_guest:
        hostname: '{{ hostname }}'
        username: '{{ user }}'
        password: '{{ pass }}'
        validate_certs: no
        datacenter: '{{ datacenter }}'
        name: 'testingvm'
        state: 'absent'
