---
- name: 'install observium'
  hosts: 'monitoring'
  remote_user: 'simon'
  become: yes
  become_method: 'sudo'

  roles:
    - 'prerequisites'
    - 'observium'
    - 'mysql'
    - 'folders'
    - 'apache'
    - 'misc'
