---
- hosts: plexservers
  become: true
  connection: local

  roles:
    - { role: common, tags: common }
    - { role: sas2ircu, tags: sas2ircu }
    - { role: sasutils, tags: sasutils }
    - { role: snapraid, tags: snapraid }
    - { role: mergerfs, tags: mergerfs }
    - { role: users, tags: users }
    - { role: docker, tags: docker }
    - { role: containers, tags: containers }
    - { role: netdata, tags: netdata }
    - { role: cronjobs, tags: cron }
    - { role: samba, tags: samba }
    - { role: nginx, tags: nginx }
    - { role: cronjobs, tags: cronjobs }
    - { role: bandcamp, tags: bandcamp }
