---
- name: 'download and expand observium'
  unarchive:
    src: 'http://www.observium.org/observium-community-latest.tar.gz'
    dest: '/var/www'
    remote_src: 'yes'
    owner: 'root'
    group: 'root'

- name: 'add config.php'
  template:
    src: 'config.j2'
    dest: '{{ observium_dir }}/config.php'
    owner: 'root'
    mode: '0775'
