---
- name: 'Setup cronjobs'
  cron:
    state: 'present'
    name: '{{ item.name }}'
    user: 'simon'
    special_time: 'weekly'
    job: '/usr/local/bin/youtube-dl --extract-audio --audio-format mp3 {{ item.url }} --output "{{ music_dir }}/Unsorted/{{ item.directory }}/%(title)s.%(ext)s"'
  loop: '{{ cronjobs }}'
