---
- name: 'enable non-free on Debian'
  when: '(ansible_distribution == "Debian")'
  lineinfile:
    path: '/etc/apt/sources.list'
    regexp: '^deb http://ftp.uk.debian.org/debian/ {{ ansible_distribution_release }} main'
    line: 'deb http://ftp.uk.debian.org/debian/ {{ ansible_distribution_release }} main non-free'

- name: 'install dependancies'
  when: '(ansible_distribution == "Ubuntu" and ansible_distribution_version >= "16.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")'
  apt:
    name:
      - 'libapache2-mod-php7.0'
      - 'php7.0-cli'
      - 'php7.0-mysql'
      - 'php7.0-mysqli'
      - 'php7.0-gd'
      - 'php7.0-mcrypt'
      - 'php7.0-json'
      - 'php-pear'
      - 'snmp'
      - 'fping'
      - 'mysql-server'
      - 'mysql-client'
      - 'python-mysqldb'
      - 'rrdtool'
      - 'subversion'
      - 'whois'
      - 'mtr-tiny'
      - 'ipmitool'
      - 'graphviz'
      - 'imagemagick'
      - 'apache2'
      - 'libvirt-bin'
      - 'snmp-mibs-downloader'
    state: 'latest'
    update_cache: yes

- name: 'install dependancies'
  when: '(ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")'
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: yes
  with_items:
    - 'libapache2-mod-php5'
    - 'php5-cli'
    - 'php5-mysql'
    - 'php5-gd'
    - 'php5-mcrypt'
    - 'php5-json'
    - 'php-pear'
    - 'snmp'
    - 'fping'
    - 'mysql-server'
    - 'mysql-client'
    - 'python-mysqldb'
    - 'rrdtool'
    - 'subversion'
    - 'whois'
    - 'mtr-tiny'
    - 'ipmitool'
    - 'graphviz'
    - 'imagemagick'
    - 'libvirt-bin'
    - 'snmp-mibs-downloader'
