---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Check Nginx is running
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 80
    delay: 3
    timeout: 60
