---
- name: 'install docker-compose binary'
  when: 'install_docker|succeeded'
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
    dest: '/usr/local/bin/docker-compose'
    mode: '0755'

- name: 'install docker-py'
  pip:
    name: 'docker-py'
    state: 'present'
