---
- name: Get latest MergerFS version
  shell: curl -s https://api.github.com/repos/trapexit/mergerfs/releases/latest | jq -r ".tag_name"
  args:
    executable: /bin/bash
    warn: no
  changed_when: false
  register: mergerfs_version
  ignore_errors: yes

- name: Download and install MergerFS
  apt:
    deb: "https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_version.stdout }}/mergerfs_{{ mergerfs_version.stdout }}.{{ ansible_distribution }}-{{ ansible_distribution_release }}_amd64.deb"

- name: Mount disks
  mount:
    state: present
    src: "{{ mergerfs.source_mounts | join(':') }}"
    path: "{{ mergerfs.pool_mount }}"
    fstype: fuse.mergerfs
    opts: "{{ mergerfs.opts | join(',') }}"
    backup: yes
