---
- name: Get latest ctop URL
  shell: curl -s https://api.github.com/repos/bcicen/ctop/releases/latest | jq -r ".assets[] | select(.name | test(\"linux-amd64\")) | .browser_download_url"
  args:
    executable: /bin/bash
  changed_when: false
  register: ctop_download_url
  ignore_errors: yes

- name: Install ctop
  get_url:
    url:  "{{ ctop_download_url.stdout | default('https://github.com/bcicen/ctop/releases/download/v0.7.1/ctop-0.7.1-linux-amd64',true) }}"
    dest: /usr/local/bin/ctop
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no
  ignore_errors: yes
