---
- name: 'Add data disks to fstab'
  blockinfile:
    path: '/etc/fstab'
    backup: yes
    marker: '# {mark} Snapraid Data Disks'
    insertafter: 'EOF'
    block: |
      UUID={{ disks.8.uuid }} {{ item.mount }}     ext4    defaults        0       2
  with_items:
    - '{{ snapraid_data_disks }}'

- name: 'Add Parity disks to fstab'
  blockinfile:
    path: '/etc/fstab'
    backup: yes
    marker: '# {mark} Snapraid Parity Disks'
    insertafter: 'EOF'
    block: |
      UUID={{ disks.11.uuid }} {{ item }}     ext4    defaults        0       2
  with_items:
    - '{{ snapraid_parity_disks }}'
