---
- name: Create disks mounts
  file:
    path: "{{ item.value.mount }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop: "{{ snapraid.disks|dict2items }}"
  loop_control:
    label: "{{ item.value.mount }}"

- name: Add Snapraid repository
  apt_repository:
    repo: ppa:tikhonov/snapraid
    state: present
    update_cache: yes

- name: Install Snapraid
  apt:
    name: snapraid
    state: present
    force: yes

- name: Configure Snapraid
  template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: 0640
