---
- name: 'create log folder'
  file:
    name: '{{ item.name }}'
    state: 'directory'
    mode: '0775'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  with_items:
    - { name: '{{ logs_dir }}', owner: 'root', group: 'root' }
    - { name: '{{ rrd_dir }}', owner: 'www-data', group: 'www-data' }
