---
- name: Uninstall 'docker-py' pip module
  pip:
    name: docker-py
    state: absent
    executable: pip3
  ignore_errors: yes

- name: Add Docker GPG key
  apt_key:
    id: 0EBFCD88
    url: http://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ 'edge' if docker.repo is defined and docker.repo | lower == 'edge' else 'stable' }}"
    filename: docker
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present

- name: Install docker pip module
  pip:
    name: docker
    state: latest
    executable: pip3
  ignore_errors: yes

- name: Install Docker-Compose
  import_role:
    name: docker-compose
  tags: docker-compose

- name: Install ctop
  import_role:
    name: ctop
  tags: ctop
