---
- name: 'add users to observium'
  command: './adduser.php {{ item.name }} {{ item.pass }} {{ item.level }}'
  args:
    chdir: '{{ observium_dir}}/'
  with_items:
    - '{{ users }}'

- name: 'add hosts to monitor'
  command: './add_device.php {{ item.host }} {{ item.string }} v2c'
  args:
    chdir: '{{ observium_dir}}/'
  with_items:
    - '{{ devices }}'

- name: 'initial discovery'
  command: './discovery.php -h all'
  args:
    chdir: '{{ observium_dir}}/'

- name: 'initial poll'
  command: './poller.php -h all'
  args:
    chdir: '{{ observium_dir}}/'

- name: 'setup cron job'
  template:
    src: 'cron.j2'
    dest: '/etc/cron.d/observium'
    owner: 'root'
    mode: '0640'

- name: 'modify snmp config'
  when: '(ansible_distribution == "Debian")'
  lineinfile:
    path: '/etc/snmp/snmp.conf'
    regexp: '^mibs :'
    line: 'mibdirs {{ observium_dir }}/mibs:{{ observium_dir }}/mibs/net-snmp'
